# Generated by Django 4.2 on 2023-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.RemoveField(
            model_name='visitdetails',
            name='host',
        ),
        migrations.RemoveField(
            model_name='visitdetails',
            name='visitor',
        ),
        migrations.AddField(
            model_name='visitor',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='VisitDetails',
        ),
    ]
