# Generated by Django 4.2 on 2023-05-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_delete_purpose_remove_visitdetails_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
